openapi: 3.0.1
info:
  title: Ride-Sharing API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
paths:
  /users/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    UserRegistration:
      type: object
      properties:
        name: { type: string, example: Alice }
        email: { type: string, example: alice@example.com }
        password: { type: string, example: password123 }
        phone_number: { type: string, example: 123-456-7890 }
    UserResponse:
      type: object
      properties:
        id: { type: string, format: uuid }
        name: { type: string }
        email: { type: string }
        phone_number: { type: string }
        created_at: { type: string, format: date-time }
    Error:
      type: object
      properties:
        error: { type: string }