/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package view.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param error 
 */


data class ErrorViewModel (

    @field:JsonProperty("error")
    val error: kotlin.String? = null

)

